stages:
  - deploy

# Running a test pipeline on the GP mirror every commit
trigger-pipeline:
  stage: deploy
  script:
    - curl -X POST -F token=${GP_MIRROR_TOKEN} -F ref=master https://git.cs.kent.ac.uk/api/v4/projects/2924/trigger/pipeline && true
